### PR TITLE
fix(hydrate): safety checks when hydrating

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? 
add json checks for wfinfo data hydration to prevent blocking server startup

---

### Reproduction steps

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Maintenance]**

### CODE REVIEW

**Comment by AyAyEm** [comment]
Well sorry to say but the CI seems to be cursed, it doesn't give any errors in two completely different machines, and it seems to always give one here. Let me know when you figure it out, because i have no idea of what's happening.

**Comment by TobiTenno** [comment]
yeah, i'm guessing it's just not hydrating properly so it's getting a string.

**Comment by TobiTenno** [comment]
@AyAyEm aaand this is why we have tests. i messed up the insertion key. that would've been a bad day if it'd deployed

**Review by AyAyEm — APPROVED** [review]

**Pull request merged**
